### ISSUE TITLE
Broken notebook link in PEFT README

### ISSUE THREAD

**Issue by mdagost** [huggingface/smol-course#113]
The notebook link and the colab notebook link are broken for the "Load LORA Adapters" section;  they point to a file called `load_lora_adapter_example.ipynb` but it should be `load_lora_adapter.ipynb`.

**Comment by mdagost** [comment]
`load_lora_adapter_example.ipyn` is referenced in `lora_adapters.md` too.

**Comment by burtenshaw** [comment]
Thanks for reporting!
