### ISSUE TITLE
Broken link for VLM notebook

### ISSUE THREAD

**Issue by alvarobartt** [huggingface/smol-course#127]
## Description

The VLM Jupyter Notebook link in https://github.com/huggingface/smol-course/tree/main/5_vision_language_models#exercise-notebooks is broken i.e. HTTP 404; and as it's not there yet, not sure the idea was to directly point to TRL instead or just point to https://github.com/huggingface/smol-course/blob/main/5_vision_language_models/notebooks/vlm_sft_sample.ipynb.

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/31417225-bf81-487b-be95-ac9190f82f65" />

cc @sergiopaniego @burtenshaw

**Comment by burtenshaw** [comment]
Thanks for reporting @alvarobartt
