### ISSUE TITLE
Add prompt masking in sft

### ISSUE THREAD

**Issue by dailydaniel** [huggingface/smol-course#23]
It seems like an important step to set up labels for sft, or at least add a link to a third-party guide and a hint that in the hard part this is also worth doing (especially for a small model).

**Comment by burtenshaw** [comment]
Thanks for your feedback. The SFTTrainer handles prompt masking so we elected to omit it. But it should definitely be referenced. Would you like to collaborate on this in a PR?

**Comment by dailydaniel** [comment]
@burtenshaw It seemed to me that by default the prompt is not masked, so I always masked it through labels. If this is relevant, then I will gladly create a PR.

**Comment by burtenshaw** [comment]
If you found it relevant, then it's worth improving. We're kind of using PRs as a study tool.

Could you open a PR with a small change or reference that mentions prompt masking, and we can go from there.

**Comment by dailydaniel** [comment]
@burtenshaw ok, no problem
