### ISSUE TITLE
Missing crucial information in "Exercise: Process a dataset for SFT" in chat_templates_example.ipynb notebook

### ISSUE THREAD

**Issue by fairydreaming** [huggingface/smol-course#30]
In [chat_templates_example.ipynb](http://192.168.18.8:8888/notebooks/1_instruction_tuning/notebooks/chat_templates_example.ipynb) there is an exercise that involves converting the dataset into chatml format.

In my opinion the exercise description misses several crucial details:
- It is never said that SmolLM2-135M model uses ChatML chat template. The only information we have is `ChatML is one such template format` (from chat_templates.md). How the course participant will know that he can use SmolLM2 tokenizer object to apply ChatML chat template? Or do you expect it to be done another way?
- The exercise description says: Convert the `HuggingFaceTB/smoltalk` dataset into chatml format. But should the output be text or tokens? What is the expected way to store the result of applying the chat template to a given sample? There is no information about this and no earlier examples showing how it could be done.

From the PRs I see that course participants are already quite confused about this.

**Comment by burtenshaw** [comment]
Thanks for this feedback. Would you like to open a PR on these changes?

**Comment by fairydreaming** [comment]
> Thanks for this feedback. Would you like to open a PR on these changes?

I'm afraid it's not possible without knowing the intentions of the original author (what is the expected solution).

**Comment by fairydreaming** [comment]
> Thanks for this feedback. I'll open a PR improving this information in the notebook. Which PR did you think also struggled with this?

Well, I examined already present [SUBMISSION] PRs and in the first exercise in `process_dataset()` they all simply return the sample dictionary without any changes to it. There is no application of the chat template in provided solutions. 

But the exercise description says "Convert the `HuggingFaceTB/smoltalk` dataset into chatml format." By "chatml format" I assume ChatML chat template format, so I guess application of the chat template shall be present in the solution. 

On the other hand, in the `process_dataset()` function we have `TODO: 🐢 Convert the sample into a chat format`. What's the "chat format"? Why not "chatml format"?

**Comment by fairydreaming** [comment]
@burtenshaw I checked the second notebook [sft_finetuning_example.ipynb](http://192.168.18.8:8888/notebooks/1_instruction_tuning/notebooks/sft_finetuning_example.ipynb) and found this:

`# TODO: 🦁 If your dataset is not in a 'chatml' format, you will need to process it. Refer to the [module](../chat_templates.md)`

Does it mean that `HuggingFaceTB/smoltalk` is already in the `chatml` format? Perhaps there is some fundamental misunderstanding there about what is the `chatml` format. Does the course use this to name a list of dictionaries with 'role' and 'content' key/value pairs?

**Comment by burtenshaw** [comment]
Thanks for your help on this @fairydreaming. I refactored and moved those exercises around a lot, and hadn't noticed that they stopped making sense.
