### ISSUE TITLE
Missing examples with Llama 3.2 model in chat_templates_example.ipynb notebook

### ISSUE THREAD

**Issue by fairydreaming** [huggingface/smol-course#33]
The [chat_templates_example.ipynb](https://github.com/huggingface/smol-course/blob/main/1_instruction_tuning/notebooks/chat_templates_example.ipynb) notebook starts with:

> Exploring Chat Templates with SmolLM2 and Llama 3.2
> 
> This notebook demonstrates how to use chat templates with the SmolLM2 and Llama 3.2 models.

So where's the Llama 3.2 part?

**Comment by burtenshaw** [comment]
Good spot. An earlier draft compared the two models.
