### ISSUE TITLE
Unclear first task

### ISSUE THREAD

**Issue by thilomichael** [huggingface/smol-course#4]
Hi, 

thank you so much for this course!
I'm currently trying to do the first task as defined in [1_instruction_tuning/README.md](../blob/main/1_instruction_tuning/README.md). There, both tasks say

```
🐢 Convert the openai/gsm8k dataset into chatml format
🐕 Convert the openai/gsm8k dataset into chatml format
```

In the according notebook ([/1_instruction_tuning/notebooks/chat_templates_example.ipynb](../blob/main/1_instruction_tuning/notebooks/chat_templates_example.ipynb)), the task also says gsm8k both times. But in the code I see the smoltalk dataset.

Is this a mistake or am I misunderstanding the task somehow?

**Comment by burtenshaw** [comment]
Sorry about that, it's human error. The 🐢 difficulty should use the smol-talk dataset.
