### ISSUE TITLE
multiple version of dependencies causes installation failure

### ISSUE THREAD

**Issue by bgrayburn** [huggingface/smol-course#46]
[This Commit](https://github.com/huggingface/smol-course/commit/b260df520695c6424302bf778dc0d22845f8ef83) looks like it duplicated all the requirements except for `yarl` which has a new version. As a result installation fails.

Thank you for creating this awesome course!

**Comment by bgrayburn** [comment]
made a pr [here](https://github.com/huggingface/smol-course/pull/47)

**Comment by burtenshaw** [comment]
Thanks for spotting this.
