### ISSUE TITLE
lighteval notebook requirements

### ISSUE THREAD

**Issue by sylvain471** [huggingface/smol-course#55]
Hello,

thanks for putting together this course!

The notebook on lighteval seems promising unfortunately I can't find the combination  of package versions to run it properly

any `requirements.txt` to help get started?

**Comment by burtenshaw** [comment]
Thanks for the comment @sylvain471. You'll see from the roadmap in the readme that we're still working on some chapters. Here's the issue for evaluation:

https://github.com/huggingface/smol-course/issues/42
