### ISSUE TITLE
What's the minimum hardware requirement needed to take this course comfortably? 

### ISSUE THREAD

**Issue by tifa365** [huggingface/smol-course#70]
First of all, thanks again for providing this great course for free and putting so much work and effort into it, I really appreciate it!

The issue: When I read the course description, I couldn't find any info which hardware is needed to follow this course. I gave it a shot and tried smol with my 16gb CPU machine (Linux). SMOL inference worked, but it tooks minutes to create an answer by the model. I guess from looking at the time of inference alone, that training the model might be impossible on a CPU?  

I would love to see some general advice and guidelines how to follow this course: E. g., is a Mac with Metal enough to train smol? Shall I give a GPU on the free tier of Colab a try, or better use the paid tier or even a completely different service such as renting a GPU short-term? 

Are there alternatives to finetuning the model on lesser hardware, such as LORA and the unsloth library? A very general "How to run this" section would be very helpful.

**Comment by burtenshaw** [comment]
We're still working on hardware requirements, but in general, it requires a GPU with at least 16gb of VRAM. You can access this for free via google colab.

> I guess from looking at the time of inference alone, that training the model might be impossible on a CPU?
That's correct.

> E. g., is a Mac with Metal enough to train smol?
That's correct.

> Are there alternatives to finetuning the model on lesser hardware, such as LORA and the unsloth library? 
We cover LoRA in module 3. So if you follow the course, you'll get the skills to trained on reduced hardware.

**Comment by burtenshaw** [comment]
We have a discord channel: https://discord.com/channels/879548962464493619/1313889336907010110
HF invite link: https://discord.gg/hugging-face-879548962464493619

**Comment by tifa365** [comment]
Answered.
